# -*- coding: utf-8 -*-
"""ns 13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlXTxc__BYyIkgcckLLkaC2oU7RyLU5X
"""

number = int(input('please enter a number '))
counter = 0
for i in range(1, 14):
  if number % i == 0:
       counter += 1

if (number == 0) or (number ==1) or (counter > 2):
  print(number, "is not a Prime number")
else:
  print(number, "is a Prime number")

rows = 5

for i in range(1, rows+1):
    for j in range(1, i+1):
        print(j, end =' ')
    print()

rows = 5

for i in range(1, rows+1):
print(i)

rows = 5

for i in range(1, rows+1):
  print(i)

rows = 5

for i in range(1, rows+1):
  print(rows)

rows = 5

for i in range(1, rows+1):
   for j in range(1, i+1):
    print(i)

rows = 5

for i in range(1, rows+1):
   for j in range(1, i+1):
    print(j)

rows = 5

for i in range(1, rows+1):
   for j in range(1, i+1):
    print(1, end=' ')

print()

rows = 5

for i in range(1, rows+1):
    for j in range(1, i+1):
       print(1, end=' ')

    print()

rows = 5

for i in range(1, rows+1):
    for j in range(1, i+1):
       print(j, end=' ')

    print()

rows = 5

for i in range(1, rows+1):
    for j in range(1, i+1):
       print(j, end=' ')

    print('*')

rows = 5

for i in range(1, rows+1):
    for j in range(1, i+1):
       print(*, end=' ')

    print()

rows = 5

for i in range(1, rows+1):
    for j in range(1, i+1):
       print('*', end=' ')

    print()

rows = int(input("How many rows?: "))
column = int(input("How many clumns?: "))
symbol = input("what symbol? ")

for r in range(rows):
  for c in range(1, r+1):
    print(symbol, end='')
  print()

rows = int(input("How many rows?: "))
column = int(input("How many clumns?: "))
symbol = input("what symbol? ")

for r in range(rows):
  for c in range(rows):
    print(symbol, end='')
  print()

x='yes'
for i in x:         #burası benim çalışmam burayı geç sonra üzerinde çalış
  for j in x:
    print(x)

num=int(input("Enter a number: "))
print("")
for i in range(1,num):
        print("*"*i)
for j in range(0,num):
        print("*"*(num-j))

ls1 = list(range(1,6))
ls1

"""List comprehension"""

ls2 = ls1**2
ls2

ls2=[]
for i in ls1:
  ls2.append(i**2)
  print(ls2)

ls2=[]
for i in ls1:
  ls2.append(i**2),
print(ls2)

ls3 = [i**3 for i in ls1]
ls3

tb2= [i*2 for i in ls1]
tb2

tb7 = [i*7 for i in ls1]
tb7

tb13 = [i*13 for i in range(14)]
tb13

tb4_3 =[(i*4)**3 for i in range(13)]
tb4_3  # (table of 4 )**3

1%2

2%2

n = int(input('please enter an nteger to check'))
if n % 2: 
  print('odd')
else:
  print('even')

"""ternary if statement

"""

n = int(input('please enter an nteger to check'))
'odd' if n % 1 else 'even'

ls_odd = [x for x in ls1 if x %2]
ls_odd

ls_even = [x for x in ls1 if not x%2]
ls_even

double_char = [i*2 for i in 'Clarusway']
double_char

double_char = [i*2 for i in 'Clarusway' if i in ['a', 'u' ]
double_char

abc  

